### PR TITLE
add Latvia for benchmarks

### PR DESCRIPTION
**Pull request by danielnaumau**

### CODE REVIEW

**Comment by Donatas-L** [comment]
We don't support Latvia ATM

**Comment by danielnaumau** [comment]
> We don't support Latvia ATM

I need it for benchmarks

**Comment by mjanuszkiewicz-tt** [comment]
You can manually implement the `Country` interface to support whatever map you want

**Comment by danielnaumau** [comment]
> You can manually implement the `Country` interface to support whatever map you want

Aaa, that's why you reworked it ?

**Comment by mjanuszkiewicz-tt** [comment]
Yes.

**Comment by danielnaumau** [comment]
cool, then I'll close this pr

**Pull request closed without merging**
